### ISSUE TITLE
Broken Link on factbook.github.io

### ISSUE THREAD

**Issue by ContactBishal** [geraldb/help#1]
Was looking into scraping a few items from the subpages of http://factbook.github.io/ and turns links are broken

So far, I've found that the below 2 links return the 404 - page not found error message: 
http://factbook.github.io/cc
http://factbook.github.io/sk

Cheers!

**Comment by geraldb** [comment]
You do NOT need to scrape the html page(s) -you can find the factbook (country profile) datasets in json (updated every week) here => https://github.com/factbook/factbook.json

**Comment by geraldb** [comment]
@ContactBishal  if you still have questions on factbook, please open a new ticket here <https://github.com/factbook/factbook/issues>
